name: Build, test, package

on: [push,pull_request]

jobs:
  cxx-build-workflow:
    uses: InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-cxx.yml@v5.4.6
    with:
      itk-module-deps: 'MeshToPolyData@43338b42866c7e155d46c32d0658383d10ab3082:BSplineGradient@fccce5321a69b1fe249ba5fa18c3d92a99eab485:HigherOrderAccurateGradient@7c074d12718a7de9e7219b2ce27415a590411e72:SplitComponents@7a1e19d1f798e58929344f69dcd371b82c28fba7:Strain@7d56db926c59021851da80dd056469e3a83f8774'
      warnings-to-ignore: "\"pointer is null\" \"in a call to non-static member function\" \"ignoring duplicate libraries\""
      
  python-build-workflow:
    uses: InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-package-python.yml@v5.4.6
    with:
      itk-wheel-tag: 'v5.4.6'
      itk-python-package-tag: 'v5.4.6'
      test-notebooks: false
      itk-module-deps: 'InsightSoftwareConsortium/ITKMeshToPolyData@43338b42866c7e155d46c32d0658383d10ab3082:InsightSoftwareConsortium/ITKBSplineGradient@fccce5321a69b1fe249ba5fa18c3d92a99eab485:InsightSoftwareConsortium/ITKHigherOrderAccurateGradient@7c074d12718a7de9e7219b2ce27415a590411e72:InsightSoftwareConsortium/ITKSplitComponents@7a1e19d1f798e58929344f69dcd371b82c28fba7:KitwareMedical/ITKStrain@7d56db926c59021851da80dd056469e3a83f8774'
    secrets:
      pypi_password: ${{ secrets.pypi_password }}
