name: Build, test, package

on: [push,pull_request]

jobs:
  cxx-build-workflow:
    uses: InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-cxx.yml@v5.4.2
    with:
      itk-module-deps: 'MeshToPolyData@7c9812527af5e061510ed5f5709da191a50e122a:BSplineGradient@73dcf827d76bbf2a36d08784d421b234fb630c80:HigherOrderAccurateGradient@ffb1cd47ddea117e3bc76ee075415efb784afd41:SplitComponents@539fcd8faca472c760a567c041cb53c610cd9108:Strain@1397eb6b4ce6d0e789af8ecc2fbe6cdf889e63ab'
      warnings-to-ignore: "\"pointer is null\" \"in a call to non-static member function\" \"ignoring duplicate libraries\""
      
  python-build-workflow:
    uses: InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-package-python.yml@v5.4.2
    with:
      itk-module-deps: 'InsightSoftwareConsortium/ITKMeshToPolyData@7c9812527af5e061510ed5f5709da191a50e122a:InsightSoftwareConsortium/ITKBSplineGradient@73dcf827d76bbf2a36d08784d421b234fb630c80:InsightSoftwareConsortium/ITKHigherOrderAccurateGradient@ffb1cd47ddea117e3bc76ee075415efb784afd41:InsightSoftwareConsortium/ITKSplitComponents@539fcd8faca472c760a567c041cb53c610cd9108:KitwareMedical/ITKStrain@1397eb6b4ce6d0e789af8ecc2fbe6cdf889e63ab'
    secrets:
      pypi_password: ${{ secrets.pypi_password }}
